name: Publish Beta Version

on:
  push:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm i --force

      - name: Generate beta version
        id: version
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Generate beta version with timestamp
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          BETA_VERSION="${CURRENT_VERSION}-beta.${TIMESTAMP}"

          echo "beta_version=${BETA_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated beta version: ${BETA_VERSION}"

          # Update package.json with beta version
          npm version ${BETA_VERSION} --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Update package metadata for beta
        run: |
          # Add beta tag to package.json
          node -e "
            const pkg = require('./package.json');
            pkg.publishConfig = { ...pkg.publishConfig, tag: 'beta' };
            require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Publish to npm (beta)
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Comment on commit
        uses: actions/github-script@v7
        with:
          script: |
            const betaVersion = '${{ steps.version.outputs.beta_version }}';
            const message = `🚀 Beta version \`${betaVersion}\` has been published to npm!

            Install with:
            \`\`\`bash
            npm install @openlettermarketing/olc-react-sdk@beta
            \`\`\`

            [View on npm](https://www.npmjs.com/package/@openlettermarketing/olc-react-sdk/v/${betaVersion})`;

            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: message
            });

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: '❌ Beta publication failed. Check the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
            });
