name: Publish Production Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}  # Remove 'v' prefix if present
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION} from tag: ${TAG_NAME}"

      - name: Send Deployment Started Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":test_tube: Production Workflow Test (Beta) Started",
              "blocks": [
                {
                    "type": "section",
                    "text": { "type": "mrkdwn", "text": ":test_tube: :test_tube: *Production Workflow Test* (Publishing as Beta) Started :test_tube: :test_tube:" }
                },
                {
                  "type": "context",
                  "elements": [
                    { "type": "mrkdwn", "text": ":male-factory-worker: *Started By:* ${{ github.actor }}" },
                    { "type": "mrkdwn", "text": ":label: *Tag:* ${{ steps.version.outputs.tag_name }}" },
                    { "type": "mrkdwn", "text": ":warning: *Mode:* Testing (Beta Release)" }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --force

      - name: Update package.json version
        run: |
          # Add -beta suffix for testing
          BETA_VERSION="${{ steps.version.outputs.version }}-beta.$(date +%Y%m%d%H%M%S)"
          echo "beta_version=${BETA_VERSION}" >> $GITHUB_OUTPUT
          echo "Testing with beta version: ${BETA_VERSION}"
          npm version ${BETA_VERSION} --no-git-tag-version --allow-same-version

      - name: Build package
        run: npm run build

      - name: Commit build changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "chore: update build artifacts for v${{ steps.version.outputs.version }} [skip ci]"
          git push origin HEAD

      - name: Update package metadata for beta testing
        run: |
          # Add beta tag to package.json for testing
          node -e "
            const pkg = require('./package.json');
            pkg.publishConfig = { ...pkg.publishConfig, tag: 'beta' };
            require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Publish to npm (beta for testing)
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send Deployment Completed Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":white_check_mark: Production Workflow Test (Beta) Completed",
              "blocks": [
                {
                    "type": "section",
                    "text": { "type": "mrkdwn", "text": ":white_check_mark: :white_check_mark: *Production Workflow Test* (Published as Beta) Completed :white_check_mark: :white_check_mark:" }
                },
                {
                  "type": "section",
                  "fields": [
                    { "type": "mrkdwn", "text": "*Original Tag:*\n${{ steps.version.outputs.tag_name }}" },
                    { "type": "mrkdwn", "text": "*Beta Version:*\n${{ steps.version.outputs.beta_version }}" }
                  ]
                },
                {
                  "type": "section",
                  "text": { "type": "mrkdwn", "text": "*Links:*\n• <https://www.npmjs.com/package/@openlettermarketing/olc-react-sdk/v/${{ steps.version.outputs.beta_version }}|NPM Package (Beta)>\n• <https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.tag_name }}|GitHub Release>" }
                },
                {
                  "type": "context",
                  "elements": [
                    { "type": "mrkdwn", "text": ":male-factory-worker: *Released By:* ${{ github.actor }}" },
                    { "type": "mrkdwn", "text": ":warning: *Note:* This was a test run - published as beta" }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Notify on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":x: Production Workflow Test (Beta) Failed",
              "blocks": [
                {
                    "type": "section",
                    "text": { "type": "mrkdwn", "text": ":x: :x: *Production Workflow Test* (Beta Mode) Failed :x: :x:" }
                },
                {
                  "type": "context",
                  "elements": [
                    { "type": "mrkdwn", "text": ":male-factory-worker: *Started By:* ${{ github.actor }}" },
                    { "type": "mrkdwn", "text": ":link: *Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>" },
                    { "type": "mrkdwn", "text": ":label: *Tag:* ${{ steps.version.outputs.tag_name }}" }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
